/* Automatically generated by configure - do not modify! */
#ifndef FFMPEG_CONFIG_H
#define FFMPEG_CONFIG_H

#include "config_arm64.h"
//
//#if  x86_64
//#include "config_x86_64.h"
//#elif i386
//#include "config_i386.h"
//#elif arm64
//#include "config_arm64.h"
//#elif armv7
//#include "config_armv7.h"
//
//#endif

#endif /* FFMPEG_CONFIG_H */

